server:
  port: 81

spring:
  application:
    name: openapi-web-master

  #mysql连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.61.131:3306/openplatform?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6371/eureka/
  #是否显示主机名 ip
  instance:
    prefer-ip-address: true

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.openplatform.webmaster.pojo,com.openplatform.webmaster.vo