server:
  port: 10001

spring:
  application:
    name: openapi-cache

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6371/eureka/
  #是否显示主机名 ip
  instance:
    prefer-ip-address: false